var physicsdata = {
  "total_size": 4,
  "questions": [
    {
      "id": 1,
      "question": "A freely suspended magnet aligns in which direction?",
      "option1": "South-west",
      "option2": "East-west",
      "option3": "North-south",
      "option4": "North-west",
      "ans": "c",
    },
    {
      "id": 2,
      "question": "The SI unit of magnetic flux is?",
      "option1": "Dyne",
      "option2": "Tesla",
      "option3": "webner",
      "option4": "ohm",
      "ans": "c",
    },
    {
      "id": 3,
      "question":
          "The magnetic dipole moment of a magnetic dipole is given by the formula?",
      "option1": "M = m x 2I",
      "option2": "M = m + 2I",
      "option3": "M = m – 2I",
      "option4": "M = m / 2I",
      "ans": "a",
    },
    {
      "id": 4,
      "question": "What does a superconductor exhibit?",
      "option1": "Ferromagnetism",
      "option2": "Paramagnetism",
      "option3": "Diamagnetism",
      "option4": "None of above",
      "ans": "c",
    },
    {
      "id": 5,
      "question": "For which of the following is the field of view maximum?",
      "option1": "Concave mirror",
      "option2": "Convex mirror",
      "option3": "Plane mirror",
      "option4": "Cylindrical mirror",
      "ans": "b",
    },
    {
      "id": 6,
      "question":
          "If a glass prism is dipped in water, what happens to its dispersive power?",
      "option1": "Increases",
      "option2": "Decreases",
      "option3": "Does not change",
      "option4": "No effect",
      "ans": "b",
    },
    {
      "id": 7,
      "question": "Which of the following phenomenon is used in optical fibre?",
      "option1": "Refraction",
      "option2": "Diffraction",
      "option3": "Scattering",
      "option4": "Total Internal Reflection",
      "ans": "d",
    },
    {
      "id": 8,
      "question": "1 Volt = ",
      "option1": "1 Coulomb",
      "option2": "1 Newton / 1 Coulomb",
      "option3": "1 Joule / 1 Coulomb",
      "option4": "1 Newton / 1 meter",
      "ans": "c",
    },
    {
      "id": 9,
      "question":
          "The electrostatic potential on the perpendicular bisector due to an electric dipole is ?",
      "option1": "zero",
      "option2": "1 ",
      "option3": "Infinite",
      "option4": "Negative",
      "ans": "a",
    },
    {
      "id": 10,
      "question":
          "The work done against electrostatic force gets stored in which form of energy?",
      "option1": "Thermal energy ",
      "option2": "Kinetic energy",
      "option3": "Potentail energy",
      "option4": "Solar energy",
      "ans": "c",
    },
  ]
};
