var mydata = {
  "total_size": 4,
  "questions": [
    {
      "id": 1,
      "question": "1-What is the first large scale automatic computer",
      "option1": "Mark I",
      "option2": " Mark II",
      "option3": "Mark IV",
      "option4": "Mark III",
      "ans": "a",
    },
    {
      "id": 2,
      "question": "2-The era of third generation of computer was",
      "option1": "1987-1989",
      "option2": "1965-1973",
      "option3": "1965-1970",
      "option4": "1955-1960",
      "ans": "c",
    },
    {
      "id": 3,
      "question": "3-What is the first large scale automatic computer",
      "option1": "Mark I",
      "option2": " Mark II",
      "option3": "Mark IV",
      "option4": "Mark III",
      "ans": "a",
    },
    {
      "id": 4,
      "question": "The era of third generation of computer was",
      "option1": "1987-1989",
      "option2": "1965-1973",
      "option3": "1965-1970",
      "option4": "1955-1960",
      "ans": "c",
    },
    {
      "id": 5,
      "question": "The Software that is used for accounting purpose is:",
      "option1": "MS Word",
      "option2": "MS Excel",
      "option3": "MS Powerpoint",
      "option4": "MS Acess",
      "ans": "b",
    },
    {
      "id": 6,
      "question":
          "The special character that initiates the formula mode in a cell is:",
      "option1": "/",
      "option2": "=",
      "option3": "-",
      "option4": "*",
      "ans": "b",
    },
    {
      "id": 7,
      "question":
          "If we want to chane the overall design of a word document we should use:",
      "option1": "themes",
      "option2": "page layout",
      "option3": "watermark",
      "option4": "margins",
      "ans": "a",
    },
    {
      "id": 8,
      "question": "Software are mostly protected under:",
      "option1": "parent",
      "option2": "Trademark",
      "option3": "Logos",
      "option4": "Copyright",
      "ans": "d",
    },
  ]
};
